name: ğŸ’• mirror

on:
  push:

jobs:
  mirror:
    name: ğŸ’• mirror to another location
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’• mirror to gitee
        uses: csplink/action_git_mirror/@master
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          dest_token: ${{ secrets.GITEE_TOKEN }}
          dest_repo: git@gitee.com:csplink/csplink.git
          dest: gitee
